### ISSUE TITLE
Resharper-like options?

### ISSUE THREAD

**Issue by OkayX6** [dungpa/fantomas#114]
Hi,

Sometimes you want to enforce a specific formatting style on some pieces of code, and don't want your code formatter to mess with what you've done.

For instance, this

``` fsharp
let f x y =
    x + y

let tryGet o defaultValue =
    Option.fold (fun _ x -> x) defaultValue o
```

Gets transformed to one-liners

``` fsharp
let f x y = x + y
let tryGet o defaultValue = Option.fold (fun _ x -> x) defaultValue o
```

And thus, they get packed although it was my intention to break the line after the '=' sign.

I think this should be up to your personal preference, and ReSharper allows this.
I tried to hack the code but I couldn't understand it well enough.
If it is easy, I would like to add options such as below (see the _Do not change/Put on single line/Break line_ options?):

![resharper-line-wrap-options](https://f.cloud.github.com/assets/1169339/1779189/1f3f364e-6843-11e3-8e7e-3be1ed14cb4d.png)

**Comment by dsyme** [comment]
I'll close this as it's not very specific about what exact options to implement.  Please reopen new issues for specific options
