### ISSUE TITLE
Moving the project to fsharp organization?

### ISSUE THREAD

**Issue by dungpa** [dungpa/fantomas#125]
After one year, most of the major issues have been resolved. We are able to fully support F# 3.1, integrate to Visual Studio and integrate to FSharpBinding (in progress).

Would it make sense to move this project to fsharp organization? The purpose is to get more contributors, more discussions on future direction, etc.

/cc @dsyme

**Comment by dsyme** [comment]
@dungpa I don't know why we never transferred this to "fsprojects"....  Anyway, integration into FCS is the way to go...

Could you give me admin access to the repo so we can triage the bugs? 

thanks!
don

**Comment by dungpa** [comment]
It didn't happen because no one cared.

By the way, I added you, @vasily-kirichenko and @cartermp as collaborators so that bugs can be triaged.

**Comment by dsyme** [comment]
@dungpa No, it was my fault, sorry - I should have completed the move.  I must have been auto-forwarding emails.
