### ISSUE TITLE
Validate results of integrateComments

### ISSUE THREAD

**Issue by dungpa** [dungpa/fantomas#161]
The `integrateComments` function takes two token streams and try to align one with the other. There is a chance that stream aligning is incorrect; we need to find a way to validate the results (possibly check for loss of significant tokens).

Examples:
- https://github.com/fsprojects/VisualFSharpPowerTools/issues/845#issuecomment-62612754
- https://github.com/dungpa/fantomas/issues/126

**Comment by dsyme** [comment]
There are certainly problems with this, but we will handle via individual correctness issues
