### ISSUE TITLE
Monadic Bind (>>=) pipelining

### ISSUE THREAD

**Issue by varon** [dungpa/fantomas#173]
The Bind should probably be treated identically to the way the forward pipe operator `|>` is treated, as it's commonly used as part of pipelined expressions.

Having this included would greatly help those of us that are writing code that utilizes it.

I doubt this would be hard to implement, so if you can provide an outline of what exactly would need to be changed to do this, I'll be happy to give it a try.

I've included an example showing where the formatter trips up - this is done using the version included in Fsharp Power Tools.

```fsharp

open System

// taken from http://fsharpforfunandprofit.com/posts/computation-expressions-intro/
let strToInt = 
    Int32.TryParse >> function 
    | (true, v) -> Some v
    | (false, _) -> None

let strAdd str i = 
    match strToInt str with
    | Some v -> Some(v + i)
    | None -> None

let strAddLong _ = strAdd

let (>>=) result f = 
    match result with
    | Some v -> f v
    | None -> None
let okayToInline = strToInt "1" >>= strAdd "2" >>= strAdd "3" >>= strAdd "4"

let expectedResult =
    strToInt "1"
    >>= strAddLong "A long argument that is ignored" "2"
    >>= strAddLong "A long argument that is ignored" "2" 
    >>= strAddLong "A long argument that is ignored" "2"
    >>= strAddLong "A long argument that is ignored" "2"
    >>= strAddLong "A long argument that is ignored" "2"
    >>= strAddLong "A long argument that is ignored" "2" 


let actualResult = 
    strToInt "1" >>= strAddLong "A long argument that is ignored" "2" >>= strAddLong "A long argument that is ignored" "2" 
    >>= strAddLong "A long argument that is ignored" "2" >>= strAddLong "A long argument that is ignored" "2" 
    >>= strAddLong "A long argument that is ignored" "2" >>= strAddLong "A long argument that is ignored" "2" 
```

**Comment by dungpa** [comment]
I agree that it's a nice improvement.

Would you like to send a PR?

I think it may be very simple:

 - Add the bind operator `>>=` to this list https://github.com/dungpa/fantomas/blob/e5c3798da6ac11d752834718b7d3c22bde4105ca/src/Fantomas/FormatConfig.fs#L414
 - Add a unit test to https://github.com/dungpa/fantomas/blob/e5c3798da6ac11d752834718b7d3c22bde4105ca/src/Fantomas.Tests/OperatorTests.fs.

Thanks.
