### ISSUE TITLE
master fails to build on Windows

### ISSUE THREAD

**Issue by varon** [dungpa/fantomas#174]
I cloned the repo then entered `./build.cmd`

I receive the following errors:

```
(snipped 255 other errors before this)

256) Test Error : Fantomas.Tests.VerboseSyntaxConversionTests.verbose syntax
   Fantomas.FormatConfig+FormatException : Parsing failed with errors: [|startup (1,1)-(1,81) typecheck error internal error:
 BuildFrameworkTcImports: no resolution of 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a';
  startup (1,1)-(1,81) parameter error Could not resolve this reference. Could not locate the assembly "FSharp.Core, Version=
4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference
 is required by your code, you may get compilation errors. (Code=MSB3245)|]
   at Fantomas.CodeFormatter.parseWith(String fileName, String content) in C:\work\github\fantomas\src\Fantomas\CodeFormatter
.fs:line 33
   at Fantomas.CodeFormatter.format(Boolean isFsiFile, String sourceCode, FormatConfig config) in C:\work\github\fantomas\src
\Fantomas\CodeFormatter.fs:line 340
   at Fantomas.Tests.VerboseSyntaxConversionTests.verbose syntax() in C:\work\github\fantomas\src\Fantomas.Tests\VerboseSynta
xConversionTests.fs:line 11


Tests Not Run:
1) Ignored : Fantomas.Tests.CommentTests.should align mis-aligned comments
2) Ignored : Fantomas.Tests.CommentTests.should keep comments on else if

Running build failed.
Error:
Fake.UnitTestCommon+FailedTestsException: NUnit test failed (256).
   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\N
Unit\Sequential.fs:line 45
   at FSI_0001.Build.clo@82-4.Invoke(Unit _arg4) in C:\work\github\fantomas\build.fsx:line 83
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0014719
AssemblyInfo   00:00:00.0070480
Build          00:00:05.6185919
Total:         00:02:03.1940770
Status:        Failure
---------------------------------------------------------------------
  1) Fake.UnitTestCommon+FailedTestsException: NUnit test failed (256).
   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\N
Unit\Sequential.fs:line 45
   at FSI_0001.Build.clo@82-4.Invoke(Unit _arg4) in C:\work\github\fantomas\build.fsx:line 83
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411
```

**Comment by dungpa** [comment]
Could you try to add binding redirects from FSharp.Core 4.4.0.0 to 4.3.1.0 at https://github.com/dungpa/fantomas/blob/e5c3798da6ac11d752834718b7d3c22bde4105ca/src/Fantomas.Tests/app.config#L11?

Do you have VS 2013 installed? So far, I only use VS 2013 to build this project.

**Comment by varon** [comment]
I do have VS2013 installed. The build fails identically even with the binding redirect added: https://github.com/varon/fantomas/commit/3747a64a30cf0ab15753136be8643442166448e0

**Comment by dungpa** [comment]
Can you run the tests inside VS 2013 (using VS test runners for example)?

I don't know why FCS fails when it looks for FSharp.Core 4.4.0.0. It supposes to fall back to an older FSharp.Core version. It works on my machine since I installed VS 2015 with F# 4.0 :(.

Btw, thanks for the PR. It almost works. The test failure is due to an extra new line in the beginning https://github.com/varon/fantomas/blob/monadicbindpipelining/src/Fantomas.Tests/OperatorTests.fs#L172.

**Comment by varon** [comment]
The standard Test Explorer window shows no tests in VS2013. I suspect you probably have another test runner installed as an extension.

I'll update the other PR.

**Comment by dungpa** [comment]
Yes, I installed NUnit test adapter VS extension. TestDriven.Net test runner should work as well.

**Comment by varon** [comment]
Installing an IDE extension isn't really a fix for this, as it's not going to use the scripts that are problematic. 

To resolve this issue, it should build correctly from a fresh clone of the repository using `./build.cmd`.

**Comment by dungpa** [comment]
You're right. I will try to repro in another machine in order to fix it.

**Comment by varon** [comment]
Thanks for being a fantastically responsive and helpful maintainer. It's always good to see.

Have you tried cloning it from scratch and just hitting ./build.cmd? Do you get any errors?

**Comment by dungpa** [comment]
I can reproduce on a machine with only VS 2013. I push a workaround at https://github.com/dungpa/fantomas/tree/build (see #176). Could you please check?

To do a proper fix, we need some upstream changes at https://github.com/fsharp/FSharp.Compiler.Service.

**Comment by varon** [comment]
It works!

I'd suggest cutting down on the incredible verbosity of the FormattingPropertyTests, but that's likely a separate issue.

```

Tests run: 262, Errors: 0, Failures: 0, Inconclusive: 0, Time: 66.7105495913406 seconds
  Not run: 2, Invalid: 0, Ignored: 2, Skipped: 0

Tests Not Run:
1) Ignored : Fantomas.Tests.CommentTests.should align mis-aligned comments
2) Ignored : Fantomas.Tests.CommentTests.should keep comments on else if

Finished Target: UnitTests
Starting Target: All (==> UnitTests)
Finished Target: All

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0014696
AssemblyInfo        00:00:00.0118085
Build               00:00:08.2993823
CopyPrerequisites   00:00:00.0042791
UnitTests           00:01:08.8645443
All                 00:00:00.0000350
Total:              00:01:17.2304971
Status:             Ok
---------------------------------------------------------------------
```

**Comment by dungpa** [comment]
I mute all the logs on formatting property tests at  e3180ad.

I appreciate your feedback. If you would like to implement anything new or improve existing features, we can discuss how to do it.
