### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by ForNeVeR** [dungpa/fantomas#187]
Fantomas definitely need a support for the latest VS.

Also, where's the VS extension source code? I haven't found it in this repository.

**Comment by dungpa** [comment]
For quite some time, Fantomas has been distributed as "Source code formatting" in Visual F# Power Tools which has Vs 2015 support. The VS extension code is at https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/FormatDocumentCommand.fs.

**Comment by ForNeVeR** [comment]
Great! Thank you for the direction.

Maybe you could mention it somewhere in the user documentation.

**Comment by dungpa** [comment]
If you send a PR to update README to clarify the situation, I would be really grateful :-).

**Comment by ForNeVeR** [comment]
No problems, gimme a minute...

**Comment by dungpa** [comment]
Perfect. Thanks a lot.
