### ISSUE TITLE
Formatter doesn't work on Opaque Record Type

### ISSUE THREAD

**Issue by varon** [dungpa/fantomas#194]
The formatter seems to crash, or completely refuse to format any `.fs` file with an opaque record type.

Input:
```fsharp
module MinExample
type Example = private {Value:int; Value2:int}
```
Output:
```fsharp
module MinExample
type Example = private {Value:int; Value2:int}
```

I would expect it to work like it does without the private flag, as evidenced below:

Input:
```fsharp
module MinExample

type Example = {Value:int; Value2:int}
```
Output:
```fsharp
module MinExample

type Example = 
    { Value : int
      Value2 : int }
```

**Comment by OkayX6** [comment]
Well, when trying to reproduce this bug in unit test or FSI with the latest repro, the formatting works as expected, but not when doing it with VFPT.

I'll try to check if it still reproduces with the latest VFPT version (which has the latest Fantomas dependency).

**Comment by varon** [comment]
Thanks!

**Comment by OkayX6** [comment]
I know why. It was generating invalid F# code:

```fsharp
type Example = 
    private
    { Value : int
       Value2 : int }
```

Instead of this:
```fsharp
type Example = 
    private { Value : int
              Value2 : int }
```
