### ISSUE TITLE
Sharing knowledge to empower potential contributors

### ISSUE THREAD

**Issue by OkayX6** [dungpa/fantomas#198]
Hey @dungpa 

The number of small issues for fantomas/VFPT is growing, it is a bit disheartening, but I know that most of them don't take that much time to solve.

We are not a lot of people to know how to contribute to fantomas, but there is nothing that complex, that is why I am planning to write a few documentation notes on fantomas architecture.

I want to be the most pragmatic possible, and not spend too much time on it.

- Explaining a little bit the architecture
- Giving examples of how you/I/others implemented a feature (referring to pull requests/commits)
- Mentioning how much time it took to do it
- How to quickly get practical with the help of F# Interactive

All these things could motivate people to contribute, because they would maybe think: "Oh, I could do it myself".

Is that OK for you?

**Comment by dungpa** [comment]
I see you already did that. It's a good idea.

**Comment by OkayX6** [comment]
Thanks man, I'll now share it to the other people!
