### ISSUE TITLE
Formatting removes methods from a struct type

### ISSUE THREAD

**Issue by nightroman** [dungpa/fantomas#201]
Copied from https://github.com/fsprojects/VisualFSharpPowerTools/issues/1459

The original code before formatting (note the position of `end`, if it is after
the methods then methods are not removed on formatting):

``` fsharp
    namespace NRText
    open System

    /// Text source record.
    /// Name : Source (file) name.
    /// LineNumber : 1-based line number.
    /// CharNumber : 1-based character number.
    type TextSource =
        struct
            val Name : string
            val LineNumber : int
            val CharNumber : int
            new (name, lineNumber) = { Name = name; LineNumber = lineNumber; CharNumber = 1 }
        end

        member x.TextAsPowerShell() =
            if x.CharNumber = 0 then
                sprintf "At %s:%d" x.Name x.LineNumber
            else
                sprintf "At %s:%d char:%d" x.Name x.LineNumber x.CharNumber

        member x.TextAsVisualStudio() =
            if x.CharNumber = 0 then
                sprintf "%s(%d)" x.Name x.LineNumber
            else
                sprintf "%s(%d,%d)" x.Name x.LineNumber x.CharNumber

        override x.ToString() =
            x.TextAsVisualStudio()
```

The code after formatting, all methods are gone:

``` fsharp
    namespace NRText

    open System

    /// Text source record.
    /// Name : Source (file) name.
    /// LineNumber : 1-based line number.
    /// CharNumber : 1-based character number.
    type TextSource =
        struct
            val Name : string
            val LineNumber : int
            val CharNumber : int
            new(name, lineNumber) =
                { Name = name
                  LineNumber = lineNumber
                  CharNumber = 1 }
        end
```

**Comment by jindraivanek** [comment]
@kragt do you plan to continue working on this, or should I take care of it?

**Comment by kragt** [comment]
@jindraivanek Sorry for the (very) late reply, I've been on vacation the last week.

I'll keep working on what issues I can fix, but I had to make some wide changes to get the whole thing to compile at all on my setup, so I'm not sure if my commits are easy to merge. 

If you want, you can just grab the changes in CodePrinter.fs and use those.

**Comment by jindraivanek** [comment]
@kragt No worries :) OK, I'll continue solving other (soundness) issues and we will see. If I start solving this I'll leave a comment here.

**Comment by kragt** [comment]
If you have a fork working that you can merge from, you are welcome to grab the code from https://github.com/kragt/fantomas/commit/94b86d4062069d379cf779201a110fee0550cbbf (you don't need the AstWriter.fs, that's just for some debugging), that fixes the issue.

**Comment by jindraivanek** [comment]
OK, I have given it a try, and it works! I'll create a PR. 

Thanks for doing this and cooperation.
