### ISSUE TITLE
Validation after formatting failed after splitting single file into multiple source files

### ISSUE THREAD

**Issue by mellson** [dungpa/fantomas#202]
I was using fantomas in VS2015 with a single fs file with no problems.
But after I have split the file into seperate files each containing their logic part of the code fantomas doesn't work anymore.

The program still does exactly the same thing, but now fantomas says 

> Validation after formatting failed. The original contents is preserved.

**Comment by MaximKitsenko** [comment]
I faced with the same problem? Doesn any one know how to fix it?

**Comment by dsyme** [comment]
I'll close this issue (also, the one linked looks very different, just the same error message)
