### ISSUE TITLE
Update FCS to version 8

### ISSUE THREAD

**Issue by vasily-kirichenko** [dungpa/fantomas#203]
We'd like to update FsLint in VFPT, it uses FCS 8. Please, update Fantomas to FCS 8, too.

**Comment by dungpa** [comment]
I'm currently on vacation. Will update the NuGet package in the end of the week.

**Comment by dungpa** [comment]
Sorry for delay.
Fixed in f0af44f7140665bd14807816dfe0a18f22c6ebad, see https://www.nuget.org/packages/Fantomas/2.4.0
