### ISSUE TITLE
.NET Core 2.0 support

### ISSUE THREAD

**Issue by ErikSchierboom** [dungpa/fantomas#215]
It would be great if Fantomas was able to run on .NET Core 2.x.

**Comment by maxdeviant** [comment]
Is there anything blocking this?

**Comment by nojaf** [comment]
We don't think so, we've started the work in https://github.com/dungpa/fantomas/pull/236.

**Comment by AnthonyLloyd** [comment]
Merged now.

**Comment by ErikSchierboom** [comment]
I can confirm that with #236 merged, this issue has been fixed. Closing it.
