### ISSUE TITLE
Wrong indentation of `else` after comment

### ISSUE THREAD

**Issue by jindraivanek** [dungpa/fantomas#241]
```
if true then 1
else //comment
    if true then 2
    else 3
```

gets formatted to

```
if true then 1
else //comment
     if true then 2
else 3
```

which is compiler error.

Without comment it works:

```
if true then 1
else
    if true then 2
    else 3
```

->

```
if true then 1
else if true then 2
else 3

```

**Comment by jindraivanek** [comment]
There is test for this here: https://github.com/dungpa/fantomas/blob/a97e52164707b904906ffcec6e8c2fbf494c4954/src/Fantomas.Tests/CommentTests.fs#L300-L318 

but it is ignored.

**Comment by nojaf** [comment]
It was unclear to us why two tests are ignored, we just kept them ignore during move to dotnet core.

**Comment by jindraivanek** [comment]
Initially I thought this will be hard to fix because of how comment integration works, but then I found out we have positions of comments in `Context.Comments`, so we can use it to change output in case of comment. 

See #244 :)
