### ISSUE TITLE
Breaking of parameters of function calls between multiple lines

### ISSUE THREAD

**Issue by ovatsus** [dungpa/fantomas#41]
This is minor, but here it goes anyway.

I had this line:

```
sprintf "https://datafeeds.networkrail.co.uk/ntrod/CifFileAuthenticate?type=CIF_%s_%s_DAILY&day=%s" 
        (toc.ToUrl()) 
        (schedule.ToUrl()) 
        (schedule.ToUrl(day))    
```

And it was changed into this:

```
sprintf "https://datafeeds.networkrail.co.uk/ntrod/CifFileAuthenticate?type=CIF_%s_%s_DAILY&day=%s" 
    (toc.ToUrl()) (schedule.ToUrl()) (schedule.ToUrl(day))
```

I think the first one was more readable.
Is it possible to add an option to align the parameters that fall to another line below the first one instead of just indenting by the default?

Actually I think the best formatting for this case would be this one:

```
sprintf "https://datafeeds.networkrail.co.uk/ntrod/CifFileAuthenticate?type=CIF_%s_%s_DAILY&day=%s" 
        (toc.ToUrl()) (schedule.ToUrl()) (schedule.ToUrl(day))    
```

**Comment by dsyme** [comment]
This is a little too minor to track as a separate issue
